# Generated by Django 3.1.7 on 2021-05-22 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investalyze', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
    ]
