# Generated by Django 3.1.7 on 2021-05-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investalyze', '0002_auto_20210522_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
    ]
