# Generated by Django 3.1.7 on 2021-05-22 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investalyze', '0004_auto_20210522_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='investalyze.lot'),
        ),
    ]
